from __future__ import annotations

import json


class PromptBuilder:
    """Build prompts for AI-enhanced SQL generation and mapping repair."""

    SQL_RULES = [
        "You are an enterprise data platform SQL expert.",
        "Generate executable Hive or Spark SQL from the mapping document.",
        "SQL keywords must be uppercase.",
        "Target table names, source aliases, and field aliases must be lowercase.",
        "Prefer WITH clauses to organize source tables.",
        "Do not use SELECT * in the main query.",
        "The output must fully cover mapping.target_columns.",
        "If aggregate expressions exist, include the correct GROUP BY clause.",
        "Return SQL only. Do not add explanations. Do not use Markdown code fences.",
    ]

    SQL_ANALYSIS_RULES = [
        "你是一名企业级数据平台 SQL 拆解与优化专家。",
        "请阅读 SQL，并用简体中文解释它的业务含义和逻辑结构。",
        "请识别来源表、Join 关系、过滤条件、聚合逻辑、输出表和关键指标。",
        "请给出适用于数仓 SQL 的、可执行的优化建议。",
        "输出必须是合法 JSON，不要输出 Markdown 代码块，不要输出额外说明。",
        (
            "返回结构为："
            "{\"purpose_analysis\": [...], \"structure_breakdown\": {...}, "
            "\"optimization_suggestions\": [...], \"optimized_sql\": \"...\"}."
        ),
        "purpose_analysis 必须是中文短句数组。",
        "structure_breakdown 必须是对象，键为 select, from, join, where, group_by, order_by, window，值也请用中文解释或整理后的 SQL 片段。",
        "optimization_suggestions 必须是中文、可执行的优化建议数组。",
        "optimized_sql 必须是可执行 SQL 文本。",
    ]

    def build_sql_messages(
        self,
        mapping: dict,
        draft_sql: str,
        user_requirement: str = "",
        selected_skill: dict | None = None,
        memory_items: list[dict] | None = None,
        schema_context: dict | None = None,
    ) -> list[dict]:
        system_content = "\n".join(self.SQL_RULES)
        requirement_section = (
            f"[user_requirement]\n{user_requirement.strip()}\n\n"
            if user_requirement and user_requirement.strip()
            else ""
        )
        skill_section = ""
        if selected_skill and selected_skill.get("id") != "none":
            skill_section = (
                "[selected_skill]\n"
                f"name: {selected_skill.get('name', '')}\n"
                f"description: {selected_skill.get('description', '')}\n"
                f"sql_pattern: {selected_skill.get('sql_pattern', '')}\n"
                f"examples: {json.dumps(selected_skill.get('examples', []), ensure_ascii=False)}\n\n"
            )
        memory_section = ""
        if memory_items:
            memory_section = "[business_memory]\n"
            for item in memory_items:
                memory_section += (
                    f"- title: {item.get('title', '')}; "
                    f"description: {item.get('description', '')}; "
                    f"hint: {item.get('hint', '')}\n"
                )
            memory_section += "\n"
        schema_section = ""
        if schema_context:
            schema_section = (
                "[schema_analysis]\n"
                f"table_purpose: {schema_context.get('table_purpose', '')}\n"
                f"key_fields: {json.dumps(schema_context.get('key_fields', {}), ensure_ascii=False)}\n"
                f"reuse_suggestions: {json.dumps(schema_context.get('reuse_suggestions', []), ensure_ascii=False)}\n"
                f"recommended_skills: {json.dumps([item.get('name', '') for item in schema_context.get('recommended_skills', [])], ensure_ascii=False)}\n\n"
            )
        user_content = (
            "Below are the user requirement, the mapping document, and a draft SQL generated by a rule engine. "
            "Use both the user requirement and the mapping as the source of truth and return the final SQL. "
            "If schema analysis is provided, use it to better understand table roles, key fields, and reusable patterns.\n\n"
            f"{requirement_section}"
            f"{skill_section}"
            f"{memory_section}"
            f"{schema_section}"
            "[mapping]\n"
            f"{json.dumps(mapping, ensure_ascii=False, indent=2)}\n\n"
            "[draft_sql]\n"
            f"{draft_sql}\n"
        )
        return [
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content},
        ]

    def build_schema_analysis_messages(self, schema_text: str, input_format: str) -> list[dict]:
        system_content = "\n".join(
            [
                "You are a data warehouse schema analysis expert.",
                "Read the provided table structure input and organize it into structured metadata.",
                "Infer the likely table type, key fields, and reusable business scenarios.",
                "Output valid JSON only, with no Markdown fences and no extra commentary.",
                (
                    "Return the structure: "
                    "{\"fields\": [...], \"table_purpose\": \"...\", \"key_fields\": {...}, "
                    "\"reuse_suggestions\": [...]}."
                ),
                "fields must be an array of objects with keys name, type, description.",
                "key_fields must be an object with keys primary_candidates, join_keys, time_fields, partition_fields, metric_fields, dimension_fields.",
                "reuse_suggestions must be an array of short business-oriented suggestions.",
            ]
        )
        user_content = (
            "Analyze the following table schema input.\n\n"
            f"[input_format]\n{input_format}\n\n"
            "[schema]\n"
            f"{schema_text}"
        )
        return [
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content},
        ]

    def build_mapping_repair_messages(self, raw_mapping_text: str) -> list[dict]:
        system_content = "\n".join(
            [
                "You are a mapping repair assistant for an enterprise data platform.",
                "The input may be malformed JSON or may contain missing fields, bad quotes, comments, trailing commas, or incomplete arrays and objects.",
                "Preserve the original meaning as much as possible.",
                "Repair the input into a valid mapping JSON object that this system can consume.",
                "The top-level mapping must include task_name, target_table, target_partition, sources, and target_columns.",
                "Each item in sources must include name and alias.",
                "Each item in target_columns must include name and expression.",
                "If joins or filters are missing, use empty arrays.",
                "Return JSON only, with no Markdown and no explanation outside JSON.",
                "Return the structure: {\"diagnosis\": [...], \"normalized_mapping\": {...}}.",
                "diagnosis must be an array of short strings explaining the problems found and how they were repaired.",
            ]
        )
        user_content = (
            "Repair the following mapping input and return the required JSON structure.\n\n"
            "[raw_mapping]\n"
            f"{raw_mapping_text}"
        )
        return [
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content},
        ]

    def build_sql_analysis_messages(self, sql_text: str) -> list[dict]:
        system_content = "\n".join(self.SQL_ANALYSIS_RULES)
        user_content = (
            "请分析并优化下面这段 SQL，并严格按要求返回中文 JSON。\n\n"
            "[sql]\n"
            f"{sql_text}"
        )
        return [
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content},
        ]
