from __future__ import annotations

import json


class PromptBuilder:
    """Build prompts for AI-enhanced SQL generation and mapping repair."""

    SQL_RULES = [
        "You are an enterprise data platform SQL expert.",
        "Generate executable Hive or Spark SQL from the mapping document.",
        "SQL keywords must be uppercase.",
        "Target table names, source aliases, and field aliases must be lowercase.",
        "Prefer WITH clauses to organize source tables.",
        "Do not use SELECT * in the main query.",
        "The output must fully cover mapping.target_columns.",
        "If aggregate expressions exist, include the correct GROUP BY clause.",
        "Return SQL only. Do not add explanations. Do not use Markdown code fences.",
    ]

    def build_sql_messages(self, mapping: dict, draft_sql: str) -> list[dict]:
        system_content = "\n".join(self.SQL_RULES)
        user_content = (
            "Below are the mapping document and a draft SQL generated by a rule engine. "
            "Use the mapping as the source of truth and return the final SQL.\n\n"
            "[mapping]\n"
            f"{json.dumps(mapping, ensure_ascii=False, indent=2)}\n\n"
            "[draft_sql]\n"
            f"{draft_sql}\n"
        )
        return [
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content},
        ]

    def build_mapping_repair_messages(self, raw_mapping_text: str) -> list[dict]:
        system_content = "\n".join(
            [
                "You are a mapping repair assistant for an enterprise data platform.",
                "The input may be malformed JSON or may contain missing fields, bad quotes, comments, trailing commas, or incomplete arrays and objects.",
                "Preserve the original meaning as much as possible.",
                "Repair the input into a valid mapping JSON object that this system can consume.",
                "The top-level mapping must include task_name, target_table, target_partition, sources, and target_columns.",
                "Each item in sources must include name and alias.",
                "Each item in target_columns must include name and expression.",
                "If joins or filters are missing, use empty arrays.",
                "Return JSON only, with no Markdown and no explanation outside JSON.",
                "Return the structure: {\"diagnosis\": [...], \"normalized_mapping\": {...}}.",
                "diagnosis must be an array of short strings explaining the problems found and how they were repaired.",
            ]
        )
        user_content = (
            "Repair the following mapping input and return the required JSON structure.\n\n"
            "[raw_mapping]\n"
            f"{raw_mapping_text}"
        )
        return [
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content},
        ]
